/**
 * S-025 — Understanding Case (Caso de Comprensión)
 *
 * An Understanding Case is the container within which the methodological
 * analysis is constructed. It represents the epistemic space — the question
 * being understood — before and independently of the analytical problem
 * formulation.
 *
 * Conceptual distinction:
 *   understandingQuestion — what the analyst seeks to comprehend (epistemic).
 *   problema             — the analytical formulation of the phenomenon (methodological).
 *
 * ADR-0014: UnderstandingCase is introduced as an additive container field in
 * ProjectSnapshotPayload. It does not replace or restructure the existing
 * methodological chain. The full domain reorganization is deferred to a future sprint.
 */

// ─── Migration origin ─────────────────────────────────────────────────────────

/**
 * Identifies a case that was synthesized automatically during schema migration.
 * Present only on cases created by the 1.0.0 → 1.1.0 migration.
 * User-created cases never have this field.
 */
export interface UnderstandingCaseMigrationOrigin {
  /** Schema version from which this case was synthesized. */
  fromSchemaVersion: string;
  /** ISO-8601 timestamp of when the synthesis occurred. */
  synthesizedAt: string;
  /** The original problema string that drove the synthesis. */
  synthesizedFromProblema: string;
}

// ─── Core entity ──────────────────────────────────────────────────────────────

export type UnderstandingCaseStatus =
  | "draft"
  | "active"
  | "in-review"
  | "archived";

/**
 * A Case of Understanding — the epistemic container for a HELIOS analysis.
 *
 * Required fields:
 *   id, name, understandingQuestion, purpose, domain,
 *   status, createdAt, updatedAt.
 *
 * Optional fields:
 *   scope, description, migrationOrigin.
 *
 * migrationOrigin is present only on cases synthesized by the 1.0.0 → 1.1.0
 * migration. It is never set by user-facing code.
 */
export interface UnderstandingCase {
  id: string;
  /** Human-readable name for the case (e.g. "Crisis hídrica en Bogotá"). */
  name: string;
  /**
   * The central comprehension question — what the analyst seeks to understand.
   * Distinct from `problema` (the analytical formulation).
   */
  understandingQuestion: string;
  /** Why this case is being studied. */
  purpose: string;
  /** Disciplinary or thematic domain (e.g. "Política pública de agua"). */
  domain: string;
  /** Optional: boundaries of the analysis (temporal, geographic, thematic). */
  scope?: string;
  /** Optional: free-form elaboration of the case context. */
  description?: string;
  status: UnderstandingCaseStatus;
  createdAt: string; // ISO-8601
  updatedAt: string; // ISO-8601
  /**
   * Present only when the case was auto-generated by the 1.0.0 → 1.1.0 migration.
   * Absent on all user-created cases.
   */
  migrationOrigin?: UnderstandingCaseMigrationOrigin;
}

// ─── Service I/O ──────────────────────────────────────────────────────────────

/** Fields supplied by the user when creating a case. */
export interface UnderstandingCaseInput {
  name: string;
  understandingQuestion: string;
  purpose: string;
  domain: string;
  scope?: string;
  description?: string;
  /** Defaults to "active" when omitted. */
  status?: UnderstandingCaseStatus;
}

/** Result of validating an UnderstandingCaseInput. */
export interface UnderstandingCaseValidationResult {
  valid: boolean;
  errors: string[];
}
